#!/usr/bin/env python
import re
import subprocess

columns = 2
raws = 2
iconbar_h = 22 # 15px + buffer
border = 1 # 1px
inner_pad = 2 # 2px inner padding
title_h = 18
glyph_size = {'W':6, 'H':13}
output = subprocess.check_output(['xwininfo', '-root']).decode('utf-8')
matches = re.findall('(W|H)(idth|eight): ([0-9]+)', output)
screen_size = {'W' : 0, 'H' : 0}

for group in matches:
  screen_size[group[0]] = int(group[2])

width_c = (screen_size['W'] - 2 * columns * (border + inner_pad)) / glyph_size['W']
height_c = (screen_size['H'] - iconbar_h - 2 * raws * (border + inner_pad)
             - raws * title_h)/glyph_size['H']
xwc = width_c/columns
xhc = height_c/raws
x_size = str(xwc) + 'x' + str(xhc)
print x_size

for i in range(0, columns):
  for j in range(0, raws):
    x_pos = str((i*screen_size['W'])/columns);
    y_pos = str((j*(screen_size['H'] - iconbar_h))/raws);
    subprocess.Popen(['xterm', '-geometry', x_size + '+'+x_pos+'+'+y_pos])
